
# docker-compose -f docker-compose.yml up -d

version: "3.5"

services:
  backend:
    image: "shaharjacob/msbackend:latest"
    container_name: backend
    build:
      context: backend
      cache_from: ["shaharjacob/msbackend:latest"]
    ports:
      - "5031:5031"
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
    working_dir: /backend/app
    command: flask run --host 0.0.0.0 --port 5031
  
  webapp:
    image: "shaharjacob/mswebapp:latest"
    container_name: webapp
    build:
      context: webapp
      cache_from: ["shaharjacob/mswebapp:latest"]
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/webapp
    working_dir: /webapp
    command: npm start
    depends_on:
      - backend
